/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.TestingPeople;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Platform;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.ViewTestRequestDetailJPanel;

/**
 *
 * @author nivcodes
 */
public class TestBookingManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestBookingManageJPanel
     */
    
    private JPanel rightContainer;
    private Platform platform;
    private UserAccount loginAccount;
    private Enterprise enterprise;
    private Organization organization;
    private Role role;
    
    public TestBookingManageJPanel(JPanel rightContainer, Platform platform, UserAccount loginAccount) {
        initComponents();
        this.rightContainer = rightContainer;
        this.platform = platform;
        this.loginAccount = loginAccount;
        setValues();
        populateTestingPendingResultTable();
    }
    
    private void populateTestingPendingResultTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblTestingPendingResult.getModel();
        dtm.setRowCount(0);
        Enterprise testingPeopleEnterprise = platform.getEnterpriseDirectory().getEnterprise(Enterprise.EnterpriseType.TestingPeople);
        ArrayList<WorkRequest> bb = testingPeopleEnterprise.getWorkQueue().getWorkRequestList();
        for (WorkRequest wr : testingPeopleEnterprise.getWorkQueue().getWorkRequestList()) {
            if (wr != null) {
                TestRequest tr = (TestRequest) wr;
                Object[] row = new Object[4];
                row[0] = tr; 
                if (tr.getSampleCollector() == null) {
                    row[1] = "-";
                } else {
                    row[1] = tr.getSampleCollector();
                }
                if (tr.getSampleCollector() == null) {
                    row[2] = "-";
                } else {
                    row[2] = tr.getNucleicAcidTester();
                }
                if (tr.getNucleicAcidTestDate() == null) {
                    row[3] = "-";
                }else {
                    row[3] = tr.isPositive() == true ? "Positive" : "Negative";
                }
                dtm.addRow(row);
            }
        }
    }
    
    public void setValues() {
        this.role = loginAccount.getRole();
        this.enterprise = platform.getEnterpriseDirectory().getEnterpriseByRole(role);
        this.organization = enterprise.getOrganizationDirectory().getOrganizationByRole(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTestingPendingResult = new javax.swing.JTable();
        btnViewDetail1 = new javax.swing.JButton();
        lblWelcome4 = new javax.swing.JLabel();

        lblWelcome3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome3.setText("Testing Pending Result");

        tblTestingPendingResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status", "Sample Collector", "Nucleic Acid Tester", "Test Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTestingPendingResult);

        btnViewDetail1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnViewDetail1.setText("View Detail");
        btnViewDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetail1ActionPerformed(evt);
            }
        });

        lblWelcome4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome4.setText("All Test Database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblWelcome4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnViewDetail1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblWelcome4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnViewDetail1)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetail1ActionPerformed
        int selectedRow = tblTestingPendingResult.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a testing request!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        TestRequest tr = (TestRequest)tblTestingPendingResult.getValueAt(selectedRow, 0);

        ViewTestRequestDetailJPanel vtrdjp = new ViewTestRequestDetailJPanel(rightContainer, tr);
        CardLayout layout = (CardLayout)rightContainer.getLayout();
        rightContainer.add("ViewTestRequestDetailJPanel", vtrdjp);
        layout.next(rightContainer);
    }//GEN-LAST:event_btnViewDetail1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewDetail1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWelcome3;
    private javax.swing.JLabel lblWelcome4;
    private javax.swing.JTable tblTestingPendingResult;
    // End of variables declaration//GEN-END:variables
}
