/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Platform;
import Business.UserAccount.UserAccount;
import Business.Util.InputValidator;
import Business.Util.StretchIcon;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.text.Document;

/**
 *
 * @author shreya
 */
public class LoginJPanel extends javax.swing.JPanel {

    private JPanel mainJFrameContainer;
    private Platform platform;
    
    public LoginJPanel(JPanel mainJFrameContainer, Platform platform) {
        initComponents();
        this.mainJFrameContainer = mainJFrameContainer;
        this.platform = platform;
        displayLogo();
        addInputTextFieldListeners();
    }
    
    private void displayLogo() {
        String rootDir = System.getProperty("user.dir");
        String iconPath = rootDir + "\\src\\Resources\\logo.png";
        ImageIcon imageIcon = new StretchIcon(iconPath);
        lblLogo.setIcon(imageIcon);
    }
    
    private void addInputTextFieldListeners() {
        Document docUser = txtUserName.getDocument();
        docUser.addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                InputValidator.userNameValidate(lblUserName, txtUserName);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                InputValidator.userNameValidate(lblUserName, txtUserName);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        Document docPass = txtPassword.getDocument();
        docPass.addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                char[] passCharArray = txtPassword.getPassword();
                String password = String.valueOf(passCharArray);
                if (InputValidator.passwordValidate(password)) {
                    lblPassword.setForeground(Color.black);
                    txtPassword.setBorder(new LineBorder(Color.green));
                }else {
                    lblPassword.setForeground(Color.red);
                    txtPassword.setBorder(new LineBorder(Color.red));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                char[] passCharArray = txtPassword.getPassword();
                String password = String.valueOf(passCharArray);
                if (InputValidator.passwordValidate(password)) {
                    lblPassword.setForeground(Color.black);
                    txtPassword.setBorder(new LineBorder(Color.green));
                }else {
                    lblPassword.setForeground(Color.red);
                    txtPassword.setBorder(new LineBorder(Color.red));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 102));

        lblUserName.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 204, 204));
        lblUserName.setText("User Name");

        lblPassword.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 204, 204));
        lblPassword.setText("Password");

        btnRegister.setBackground(new java.awt.Color(65, 105, 225));
        btnRegister.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(65, 105, 225));
        btnLogin.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Avenir", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Pathology labs and diagnostic central platform");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(lblUserName)
                .addGap(18, 18, 18)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        RegisterJPanel rjp = new RegisterJPanel(mainJFrameContainer, platform);
        CardLayout layout = (CardLayout)mainJFrameContainer.getLayout();
        mainJFrameContainer.add("RegisterJPanel",rjp);
        layout.next(mainJFrameContainer);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUserName.getText();
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        if (!InputValidator.userNameValidate(username)) {
            JOptionPane.showMessageDialog(null, "Invalid input!\nUsername consists of alphanumeric characters (a-zA-Z0-9), lowercase, or uppercase.\n" +
                "Username allowed of the dot (.), underscore (_), and hyphen (-).\n" +
                "The dot (.), underscore (_), or hyphen (-) must not be the first or last character.\n" +
                "The dot (.), underscore (_), or hyphen (-) does not appear consecutively, e.g., java..regex\n" +
                "The number of characters must be between 5 to 20.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!InputValidator.passwordValidate(password)) {
            JOptionPane.showMessageDialog(null, "Invalid input!\nPassword consists of alphanumeric characters (a-zA-Z0-9), lowercase, or uppercase.\n"
                    + "At least one character of [$*#&@.].\n"
                    + "At least six characters long.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // check if the login account is system admin
        UserAccount userAccount = platform.getUserAccountDirectory().authenticateUser(username, password);
        if(userAccount == null){
            JOptionPane.showMessageDialog(null, "Invalid credentials", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!userAccount.isDeleted()) {
            CardLayout layout = (CardLayout)mainJFrameContainer.getLayout();
            mainJFrameContainer.add("workArea",userAccount.getRole().createWorkArea(mainJFrameContainer, userAccount, platform));
            layout.next(mainJFrameContainer);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
