/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

//import com.github.javafaker.Faker;
import Business.City.City;
import Business.DB4OUtil.DB4OUtil;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Platform;
import Business.Role.CDCAdminRole;
import Business.Role.CDCDataHandlerRole;
import Business.Role.CDCInfoDistributorRole;
import Business.Role.NucleicAcidTesterRole;
import Business.Role.RegisteredTestingPeopleRole;
import Business.Role.Role;
import Business.Role.SampleCollectionPeopleRole;
import Business.Role.SimulationOperatorRole;
import Business.Role.TestingPeopleAdminRole;
import Business.Role.TestingSiteAdminRole;
import Business.Role.TestingSiteDataHandlerRole;
import Business.UserAccount.UserAccount;
import Business.Util.EmailToolKit;
import Business.Util.InputValidator;
import Business.WorkQueue.TestRequest;
import Business.WorkQueue.TestSlotRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nivcodes
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Platform platform;
    /**
     * Creates new form MainJFrame2
     */
    public MainJFrame() {
        platform = dB4OUtil.retrieveSystem();
        
//        Setup application data
//        configure_app();
        
        initComponents();
        this.setSize(980, 650);
        LoginJPanel ljp = new LoginJPanel(mainJFrameContainer, platform);
        CardLayout layout = (CardLayout)mainJFrameContainer.getLayout();
        mainJFrameContainer.add("LoginJPanel",ljp);
        layout.next(mainJFrameContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJFrameContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        mainJFrameContainer.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainJFrameContainer, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainJFrameContainer;
    // End of variables declaration//GEN-END:variables

    
}
