/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.WorkQueue.TestSlotRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nivcodes
 */
public class ViewTestSlotDetailJPanel extends javax.swing.JPanel {

    private JPanel rightContainer;
    private TestSlotRequest tsr;
    
    public ViewTestSlotDetailJPanel(JPanel rightContainer, TestSlotRequest tsr) {
        initComponents();
        this.rightContainer = rightContainer;
        this.tsr = tsr;
        populateForm();
    }
    
    private void populateForm() {
        txtAbsentNum.setText(String.valueOf(tsr.calcAbsentRequests()));
        txtBookCancelledNum.setText(String.valueOf(tsr.calcBookCancelledRequests()));
        txtBookedNum.setText(String.valueOf(tsr.calcBookedRequestsHistorically() - tsr.calcBookCancelledRequests()));
        txtCapacity.setText(String.valueOf(tsr.getCapacity()));
        txtCapacityRemained.setText(String.valueOf(tsr.getCapacity() - tsr.calcBookedRequestsHistorically()));
        txtPositiveNum.setText(String.valueOf(tsr.calcPositiveRequests()));
        txtStatus.setText(tsr.getStatus());
        txtSlotReleaser.setText(tsr.getSlotReleaser().toString());
        txtSlotReleaseDate.setText(tsr.getSlotReleaseDate().toString());
        txtScheduledTestingDate.setText(tsr.getScheduledTestingDate().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPositiveNum = new javax.swing.JTextField();
        txtScheduledTestingDate = new javax.swing.JTextField();
        lblPlane1 = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        txtSlotReleaseDate = new javax.swing.JTextField();
        txtCapacityRemained = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        lblPrice1 = new javax.swing.JLabel();
        txtBookedNum = new javax.swing.JTextField();
        txtBookCancelledNum = new javax.swing.JTextField();
        lblPlane = new javax.swing.JLabel();
        lblPlane2 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtCapacity = new javax.swing.JTextField();
        lblFlightInfo = new javax.swing.JLabel();
        txtSlotReleaser = new javax.swing.JTextField();
        lblFlightNumber = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        txtAbsentNum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        txtPositiveNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPositiveNum.setEnabled(false);

        txtScheduledTestingDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScheduledTestingDate.setEnabled(false);

        lblPlane1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblPlane1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPlane1.setText("Positive People");

        lblFrom.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        lblFrom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFrom.setText("Scheduled Testing Date");

        lblDate1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblDate1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate1.setText("Test Absent Number");

        txtSlotReleaseDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSlotReleaseDate.setEnabled(false);

        txtCapacityRemained.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCapacityRemained.setEnabled(false);

        lblTo.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblTo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTo.setText("Slot Release Date");

        lblPrice1.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblPrice1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrice1.setText("Capacity remained");

        txtBookedNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBookedNum.setEnabled(false);

        txtBookCancelledNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBookCancelledNum.setEnabled(false);

        lblPlane.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblPlane.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPlane.setText("Still Booked Number");

        lblPlane2.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        lblPlane2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPlane2.setText("Book Cancelled Number");

        lblDate.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate.setText("Testing Capacity");

        btnBack.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtCapacity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCapacity.setEnabled(false);

        lblFlightInfo.setFont(new java.awt.Font("黑体", 2, 24)); // NOI18N
        lblFlightInfo.setText("Test Slot Detail");

        txtSlotReleaser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSlotReleaser.setEnabled(false);

        lblFlightNumber.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblFlightNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFlightNumber.setText("Status");

        lblPrice.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrice.setText("Slot Releaser");

        txtStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStatus.setEnabled(false);

        txtAbsentNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbsentNum.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCapacityRemained, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPositiveNum, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAbsentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCapacity)
                                .addComponent(txtSlotReleaser, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtBookedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblFlightNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtScheduledTestingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSlotReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPlane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(txtBookCancelledNum, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFlightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblFlightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFlightNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrom)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtScheduledTestingDate)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlotReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSlotReleaser)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBookedNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlane2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBookCancelledNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAbsentNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPositiveNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacityRemained)
                    .addComponent(lblPrice1))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightContainer.remove(this);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.previous(rightContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblFlightInfo;
    private javax.swing.JLabel lblFlightNumber;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblPlane;
    private javax.swing.JLabel lblPlane1;
    private javax.swing.JLabel lblPlane2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPrice1;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtAbsentNum;
    private javax.swing.JTextField txtBookCancelledNum;
    private javax.swing.JTextField txtBookedNum;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtCapacityRemained;
    private javax.swing.JTextField txtPositiveNum;
    private javax.swing.JTextField txtScheduledTestingDate;
    private javax.swing.JTextField txtSlotReleaseDate;
    private javax.swing.JTextField txtSlotReleaser;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
