/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.WorkQueue.TestRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shubank
 */
public class ViewTestRequestDetailJPanel extends javax.swing.JPanel {

    private JPanel rightContainer;
    private TestRequest tr;
    
    public ViewTestRequestDetailJPanel(JPanel rightContainer, TestRequest tr) {
        initComponents();
        this.rightContainer = rightContainer;
        this.tr = tr;
        populateForm();
    }
    
    private void populateForm() {
        txtSampleCollectionDate.setText(tr.getCollectionDate() == null ? "" : tr.getCollectionDate().toString());
        txtStatus.setText(tr.getStatus());
        if (tr.getNucleicAcidTestDate() == null) {
            txtResult.setText("");
        }else {
            txtResult.setText(tr.isPositive() == true ? "Positive" : "Negative");
        }
        txtSlotReleaseDate.setText(tr.getTestSlotRequest().getSlotReleaseDate().toString());
        txtScheduledTestingDate.setText(tr.getTestSlotRequest().getScheduledTestingDate().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFlightNumber = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtScheduledTestingDate = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtSlotReleaseDate = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblTo = new javax.swing.JLabel();
        txtSampleCollectionDate = new javax.swing.JTextField();
        lblFlightInfo = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblFlightNumber.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblFlightNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFlightNumber.setText("Status");

        lblPrice.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrice.setText("Result");

        txtScheduledTestingDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtScheduledTestingDate.setEnabled(false);

        txtStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStatus.setEnabled(false);

        lblFrom.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        lblFrom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFrom.setText("Scheduled Testing Date");

        lblDate.setFont(new java.awt.Font("微软雅黑", 1, 12)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate.setText("Sample Collection Date");

        txtSlotReleaseDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSlotReleaseDate.setEnabled(false);

        btnBack.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTo.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        lblTo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTo.setText("Slot Release Date");

        txtSampleCollectionDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSampleCollectionDate.setEnabled(false);

        lblFlightInfo.setFont(new java.awt.Font("黑体", 2, 24)); // NOI18N
        lblFlightInfo.setText("Test Request Detail");

        txtResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResult.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSampleCollectionDate)
                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblFlightNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(74, 74, 74)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtScheduledTestingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSlotReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnBack, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFlightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblFlightInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFlightNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrom)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtScheduledTestingDate)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlotReleaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSampleCollectionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtResult)))
                .addGap(45, 45, 45)
                .addComponent(btnBack)
                .addGap(194, 194, 194))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightContainer.remove(this);
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.previous(rightContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFlightInfo;
    private javax.swing.JLabel lblFlightNumber;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtSampleCollectionDate;
    private javax.swing.JTextField txtScheduledTestingDate;
    private javax.swing.JTextField txtSlotReleaseDate;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
