/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Simulation;

import Business.Platform;
import Business.Supplier.Inventory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestRequest;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author nivcodes
 */
public class InventoryMngJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InventoryMngJPanel
     */
    private JPanel rightContainer;
    private Platform platform;
    private UserAccount loginAccount;
    
    public InventoryMngJPanel(JPanel rightContainer, Platform platform, UserAccount loginAccount) {
        initComponents();
        this.rightContainer = rightContainer;
        this.platform = platform;
        this.loginAccount = loginAccount;
        populateCityCbx();
        popInventory();
        
    }
    
    private void popInventory() {
        HashMap<String, Integer> inventoryMap = platform.getInventory().getInventoryMap();
        lblSwabsQ1.setText(String.valueOf(inventoryMap.get("Swabs")));
        lblSyrQ.setText(String.valueOf(inventoryMap.get("Syringe")));
        lblcottonQ2.setText(String.valueOf(inventoryMap.get("Sterile cotton")));
        lblvialsQ3.setText(String.valueOf(inventoryMap.get("Vials")));
    }
    
    private void populateCityCbx() {
        DefaultComboBoxModel<Object> dcbm = new DefaultComboBoxModel<>();
        for (String ct : Inventory.options) {
            dcbm.addElement(ct);
        }
        cbxDisease.setModel(dcbm);
        cbxDisease.setSelectedIndex(0);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome1 = new javax.swing.JLabel();
        btnUpdqateQ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblSyrQ = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSwabsQ1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblcottonQ2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblvialsQ3 = new javax.swing.JLabel();
        jupdatedQ = new javax.swing.JTextField();
        cbxDisease = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblWelcome2 = new javax.swing.JLabel();

        lblWelcome1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome1.setText("Update Inventory");

        btnUpdqateQ.setFont(new java.awt.Font("微软雅黑", 1, 14)); // NOI18N
        btnUpdqateQ.setText("Update");
        btnUpdqateQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdqateQActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Syringes:");

        lblSyrQ.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        lblSyrQ.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSyrQ.setText("Syringes:");

        jLabel2.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Swabs:");

        lblSwabsQ1.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        lblSwabsQ1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSwabsQ1.setText("Syringes:");

        jLabel3.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Sterile cotton:");

        lblcottonQ2.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        lblcottonQ2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcottonQ2.setText("Syringes:");

        jLabel4.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Vials:");

        lblvialsQ3.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        lblvialsQ3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblvialsQ3.setText("Syringes:");

        jupdatedQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdatedQActionPerformed(evt);
            }
        });

        cbxDisease.setFont(new java.awt.Font("微软雅黑", 0, 14)); // NOI18N
        cbxDisease.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiseaseActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Choose item");

        jLabel6.setFont(new java.awt.Font("Monaco", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Updated quantity");

        lblWelcome2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcome2.setText("Inventory");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSyrQ, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblcottonQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblSwabsQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblvialsQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxDisease, 0, 210, Short.MAX_VALUE)
                            .addComponent(btnUpdqateQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jupdatedQ)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblWelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addComponent(lblWelcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(444, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSyrQ))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSwabsQ1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblcottonQ2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblvialsQ3))
                .addGap(90, 90, 90)
                .addComponent(lblWelcome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jupdatedQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(50, 50, 50)
                .addComponent(btnUpdqateQ)
                .addGap(77, 77, 77))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(lblWelcome2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(616, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdqateQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdqateQActionPerformed
        int q = Integer.parseInt(jupdatedQ.getText());
        String item = cbxDisease.getSelectedItem().toString();
        platform.getInventory().updateInventory(item, q);
        popInventory();
        JOptionPane.showMessageDialog(null, "Updated Successfully!!");
    }//GEN-LAST:event_btnUpdqateQActionPerformed

    private void jupdatedQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdatedQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jupdatedQActionPerformed

    private void cbxDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiseaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdqateQ;
    private javax.swing.JComboBox<Object> cbxDisease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jupdatedQ;
    private javax.swing.JLabel lblSwabsQ1;
    private javax.swing.JLabel lblSyrQ;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JLabel lblcottonQ2;
    private javax.swing.JLabel lblvialsQ3;
    // End of variables declaration//GEN-END:variables
}
